apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lxyz
  name: deployxyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyzpod
  template:
    metadata:
      name: podtesting 
      labels:
        app: xyzpod
    spec:
      containers:
      - name: lxyz
        image: naveenbansal/xyz:latest
        ports:
        - containerPort: 8084



        
