apiVersion: apps/v1
kind: Deployment
metadata:
name: xyz
labels:
app: xyz
namespace: kube-system

`
spec:
replicas: 2
selector:
matchLabels:
app: xyz
template:
metadata:
labels:
app: xyz
spec:
containers:
- name: xyz
image: naveenbansal/xyz:latest
ports:
- containerPort: 8084

