apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lxyz
  name: deploy_xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyzpod
  template:
    metadata:
      name: pod-testing 
      labels:
        app: xyzpod
    spec:
      containers:
      - name: lxyz
        image: naveenbansal/xyz:latest
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: service_xyz
  labels:
spec:
  type:LoadBalancer
  ports:
  - port: 8084
  selector:
    app: xyzpod
      


        
