apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz
  labels:
    app: xyz
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: xyz
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - name: xyz
        image: naveenbansal/xyz:latest
        ports:
        - containerPort: 8084

---

apiVersion: v1
kind: Service
metadata:
  name: xyz
  labels:
    
spec:
  type:ClusterIP
  selector:
    app: xyz
  ports:
  - port: 8084
    targetPort:8080
