apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xyz
  name:  
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xyz
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - name: xyz
        image: naveenbansal/xyz:latest
        ports:
        - containerPort: 8084
      
---
apiVersion: v1
kind: Service
metadata:
  name: xyz
spec:
  ports:
  - port: 8084
    targetPort:8080
  selector:
    app: xyz

        
