apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy
  name: deploy-test 
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xyz
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - name: xyz
        image: naveenbansal/xyz:latest
        ports:
        - containerPort: 8084
